services:
  translation-bot:
    build: .
    container_name: discord-translation-bot
    restart: unless-stopped
    environment:
      - ANTHROPIC_API_KEY=sk-
      - DISCORD_TOKEN=discord-token
      - NODE_ENV=production      
      - GOOGLE_GENERATIVE_AI_API_KEY=AIzaSyA1M35rKF21-NXgvu3KLI2jej1wwm9X_lA
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
