services:
  translation-bot:
    build: .
    container_name: discord-translation-bot
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
